### PR TITLE
Other Languages (Python, C#, Java) Q/A to FAQ

### PR DESCRIPTION
**Pull request by PeterTurcan**
Added a section to the User Guide FAQ on how to interface Python, C# apps to Boost - including error handling, return values, exceptions. Shorter code for Java (no error handling or return values).

### CODE REVIEW

**Comment by alandefreitas** [comment]
Did this content come from somewhere else?

Is ```cpp valid asciidoc?

Where is this content being rendered in boost.io?

**Comment by PeterTurcan** [comment]
Did this content come from somewhere else?

No, my ideas and research.

Is ```cpp valid asciidoc?

No, my bad, should be [source,cpp] - will change ASAP

Where is this content being rendered in boost.io?

Not there yet but should be in the User Guide FAQ - preview is here:
https://245.site-docs.prtest2.cppalliance.org/user-guide/faq.html

**Comment by alandefreitas** [comment]
Oh... OK. I thought that content was for the website only. Sorry. 

The content looks ok.

Just let me know when you've fixed the source code blocks then.

**Comment by joaquintides** [comment]
I find the newly added content very good.

**Comment by PeterTurcan** [comment]
@alandefreitas great - code blocks fixed/squashed @joaquintides thanks for the feedback!

**Pull request merged**
