### PR TITLE
Antora UI Updates

### PR DESCRIPTION
**Pull request by julioest**
### Description
This PR is meant to be first iteration of boost doc styling update, giving it a previous look-and-feel ui

### Notes

- Modern sans-serif font fallback stack
- Standard font size across elements and components
- Fixes https://github.com/boostorg/website-v2-docs/issues/161

### CODE REVIEW

**Review by alandefreitas — COMMENTED** [review]
I think it would be better to have a release associated with `julioest/boost-ui`'s `master` branch so that we don't have to keep updating these two files every time there's an update in `julioest/boost-ui`.

**Comment by vinniefalco** [comment]
its antora-ui not boost-ui

**Comment by vinniefalco** [comment]
This isn't going to actually be merged right? Because the playbook references a personal repository.

**Comment by alandefreitas** [comment]
> personal repository

Should we move this to a cppalliance repo for now or already a boostorg repository?

> its antora-ui not boost-ui

I think the idea is that boost-ui is what we're going to use for boostorg/website-v2-docs and antora-ui is storing a backup of the work the other guys did on that other ui bundle for the cppalliance (the other font, the original admonition, etc...).

**Comment by alandefreitas** [comment]
Also, the fonts still look different over here.

The UI bundle:

image_720

Boost.URL documentation:

image_720

**Comment by vinniefalco** [comment]
as far as I can tell we only need one UI not two.... or am I missing something?

**Comment by alandefreitas** [comment]
> as far as I can tell we only need one UI not two.... or am I missing something?

Yes. We just need one. 

I think you mentioned other UIs for standalone projects such as MrDocs in the past but I think bundles related to the C++ alliance only are outside the context of this discussion.

At some point, I told Julio I thought it could be a good idea to back up what we had before just in case. I'm not sure we really need it because we can just go back in history but anyway...

In any case, all the work is going into a single UI bundle.

**Comment by julioest** [comment]
@alandefreitas want me to port over the changes from my personal repo to my fork?

**Comment by alandefreitas** [comment]
This PR also needs to remove the antora-ui directory and update the bash scripts to stop building the UI bundle in antora-ui (that's going to happen in https://github.com/julioest/boost-ui (or whatever it becomes) now

**Comment by vinniefalco** [comment]
What does the User's Guide look like now?

**Comment by alandefreitas** [comment]
> What does the User's Guide look like now?

https://204.site-docs.prtest2.cppalliance.org/user-guide/index.html

**Comment by vinniefalco** [comment]
What is this "Merge branch 'boostorg:develop' into develop?" It looks like a merge commit... please fix the commit log for this pull request to be linear.

**Comment by julioest** [comment]
> This isn't going to actually be merged right? Because the playbook references a personal repository.

@vinniefalco, in this case, could we get a dedicated repo for Antora UI updates? Thanks!

**Comment by vinniefalco** [comment]
No, it is better to put the UI in the same repository as the documentation.

**Comment by julioest** [comment]
Roger that. I'll make the necessary changes

**Comment by julioest** [comment]
This PR didn't follow the proper Git workflow, so closing it. A new PR with the correct process will be up soon. Thanks!

**Pull request closed without merging**
