### PR TITLE
Update Antora UI styles

### PR DESCRIPTION
**Pull request by julioest**
### Description
This PR is meant to be first iteration of boost doc styling update, giving it a previous look-and-feel ui

### Notes

- Removes Cairo font
- Adds modern sans-serif font fallback stack
- Standard font size across elements and components
- Fixes https://github.com/boostorg/website-v2-docs/issues/161

### CODE REVIEW

**Comment by vinniefalco** [comment]
Where's the preview?

**Review by alandefreitas — APPROVED** [review]
LGTM

**Comment by vinniefalco** [comment]
@alandefreitas how do you know that the preview is showing exactly how it will look on the live server? It already looks different... the preview has Lunr and Search box but those are not present on live.

**Comment by alandefreitas** [comment]
> how do you know that the preview is showing exactly how it will look on the live server?

I don't. website-v2 is an independent project and I have no idea of what transformations they've implemented there. For all I know, they could even be using another UI bundle.

**Comment by vinniefalco** [comment]
Well we better figure this out then, shouldn't we?

**Comment by alandefreitas** [comment]
@joaquintides Who understands the process in website-v2 that's patching the documentation with that boost.io header?

@vinniefalco It's a good idea to figure this out because we will need it. Since this PR is about the fonts, I think the header issue is independent of and shouldn't block this PR and @julioest.

**Comment by joaquintides** [comment]
> @joaquintides Who understands the process in website-v2 that's patching the documentation with that boost.io header?

@julioest has been doing changes to this header laterly, so I guess he's the person you're looking for.

**Comment by vinniefalco** [comment]
RevSys understands it. (Frank Wiles)

**Comment by alandefreitas** [comment]
> @julioest (...) 's the person you're looking for.

Well, that would be ironic 😆

**Pull request merged**
