### PR TITLE
Update Antora UI template (#266)

### PR DESCRIPTION
**Pull request by julioest**
### Description
This PR updates the Antora UI templates to enhance the user interface and improve the overall user experience

Addresses #266

### CODE REVIEW

**Comment by vinniefalco** [comment]
needs squashing

**Review by rbbeeston — COMMENTED** [review]
can the JS code be removed now? Is there a reason to wait on it?

**Comment by vinniefalco** [comment]
This needs to be broken up into individual, functional commits. For example "flatten left nav", "adjust page controls," and so on.

**Review by alandefreitas — APPROVED** [review]

**Comment by vinniefalco** [comment]
This looks very good

**Review by rbbeeston — APPROVED** [review]
LGTM!

**Comment by vinniefalco** [comment]
how does this look good to you? some controls are broken and it does not resize correctly

**Comment by julioest** [comment]
Here's a recording of the latest functionality:

https://github.com/user-attachments/assets/b070d49d-fa60-49f8-9c30-a3e814907053

**Pull request merged**
