### PR TITLE
Integrate cppallliance/boostlook

### PR DESCRIPTION
**Pull request by alandefreitas**

### CODE REVIEW

**Comment by alandefreitas** [comment]
@julioest @rbbeeston 

I updated the PR with the `--skip-boostlook` option for gulp. So, we have three workflows:

- When pushing to the repo (CI) or building the UI bundle for the first time, the file won't be there and `gulp build` will download it.
- The bundle will reuse the file when working on the content of the components (Peter Turcan's workflow). It will attempt to update the stylesheets once an hour.
- When working on `boostlook.css` itself, you can build it with `gulp build --skip-boostlook` so that it doesn't attempt to update the local file.

This should cover all cases. I hope that's OK.

**Comment by alandefreitas** [comment]
@julioest @rbbeeston I need a review here.

To make this work, I had to study Gulp more in-depth, so I refactored the Gulp files to make them more straightforward.

As you'll see, the integration is working, but the problem is that it just looks too ugly. So, I need you guys to decide what the workflow should be now.

- Maybe you guys want me to integrate it differently in head-styles.hbs
- Maybe there's work to do in Boostlook before merging this here
- Maybe there's work to do here in site.css before merging this PR

**Comment by julioest** [comment]
@rbbeeston @alandefreitas Thanks for the notes and hard work on this!

The issue was due to old code I was experimenting with. It will be fixed once my PR is merged (https://github.com/cppalliance/boostlook/pull/1)

**Review by rbbeeston — APPROVED** [review]

**Comment by alandefreitas** [comment]
> The UI issue was due to old CSS grid code I was experimenting with. It will be fixed once my PR is merged (https://github.com/cppalliance/boostlook/pull/1).

Does that mean https://github.com/cppalliance/boostlook/pull/2 is obsolete? It'd be great if we could merge only https://github.com/cppalliance/boostlook/pull/1.

**Pull request merged**
