### PR TITLE
Add Boost Media Logo guidelines

### LINKED ISSUE #217: Boost Mark License
Please add the following "Boost Mark License" as its own page in the Contributor's Guide.
[Boost Mark License.pdf](https://github.com/boostorg/website-v2-docs/files/14997941/Boost.Mark.License.pdf)

### PR DESCRIPTION
**Pull request by PeterTurcan**
fix #217

Added to the Documentation section of the Contributor Guide

### CODE REVIEW

**Comment by vinniefalco** [comment]
Well this is a work in progress we need to iterate on this including providing the color spec for Boost Mustard and several variations of the logo in different formats and backgrounds.

**Comment by PeterTurcan** [comment]
From a color picker, the RGB value for Mustard appears to be 255,159,0.  The CIELAB conversion of this is Lightness 82.14, (Green-Red) -23.13, and Blue-Yellow as 54.49. Would these two values work as a definition?

**Comment by vinniefalco** [comment]
No we should not try to define it, because I need to select the color from a hardcopy. That is, from a physical set of color tiles either Pantone, or whatever is in vogue these days. And from there we determine the color values in device-independent coordinates such as CIELAB or CIEXYZ. And we can also license whatever the proprietary specifications are (Pantone I guess although I don't even know if that's still around). A quick Internet search shows "Freetone" as the free replacement for Pantone so we can consider that.

This is all very nice but hardly needed this moment as there are other higher priority things to do.

**Comment by PeterTurcan** [comment]
Closing for now

**Comment by joaquintides** [comment]
@PeterTurcan could you please reopen? As per a conversation we've had on Slack, we can merge this as is and work on the color specs can be resumed later. Thank you!

**Comment by PeterTurcan** [comment]
@joaquintides Git would not let me reopen easily - so resubmitted in https://github.com/boostorg/website-v2-docs/pull/222

**Pull request closed without merging**
